title: Comifo Media
baseurl: "/comifo-media"
url: "https://comifo-media.github.io"

collections:
  films:
    output: false

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_pages"
    values:
      layout: default

plugins:
  - jekyll-paginate

paginate: 15
paginate_path: "/comifo-media/page/:num/"
