title: Comifo Media
baseurl: "/comifo-media"  # Laisse vide si ton site est à la racine du domaine
url: "https://comifo-media.github.io"  # URL de ton site GitHub Pages

collections:
  films:
    output: false

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_pages"
    values:
      layout: default
      
plugins:
  - jekyll-paginate

paginate: 15
paginate_path: "/comifo-media/page/:num/"
